Update the guide to use dev mode
OpenLiberty/guide-maven-multimodules pull request #104
Opened 2021-10-21 18:23 UTC by gkwan-ibm

LMP supports running dev mode on multiple projects. The guide is updated to demonstrate how to use it for development. 
Address issue: https://github.com/OpenLiberty/guides-common/issues/707

2021-10-25 21:04 UTC, dmuelle requested changes
ID review- see my comments in line, let me know if you have any questions or if I've misunderstood anything. Thanks!

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +A Java Platform, Enterprise Edition (Jakarta EE) application consists of modules that work together as one entity. An enterprise archive (EAR) is a wrapper for a Jakarta EE application, which consist
should it be "Jakarta Platform, Enterprise Edition..."?

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +You will learn how to establish a dependency between a web module and a Java library module. You will use Maven to package the WAR file and the JAR file into an EAR file so that you can run and test
consider formatting as a bulleted list for readability and concision

In this guide, you will learn how to: 
- establish a dependency between a web module and a Java library module, 
- use Maven to package the WAR file and the JAR file into an EAR file so that you can run and test the application on Open Liberty, and
-  use the Liberty Maven plug-in to develop a multi-module application in development mode without having to prebuild the JAR and WAR files. In development mode, your changes are automatically picked up by the running server.

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +To deploy your EAR application on an Open Liberty server, run the Maven `liberty:run` goal from the `finish` directory using the `-pl ear` or `--projects ear` flag:
are the `-pl ear` or `--projects ear` options identical? If so, is there any reason to document both? Better to document a single pathway when possible. If they are different options, why would a user choose one vs the other?

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +Normally, the [hotspot=parent file=0]`parent/child` structure would not be needed for multi-module applications, however it is better to use it here, as it allows us to better organize all of the pro
suggested edit:

Although the [hotspot=parent file=0]`parent/child` structure is not normally needed for multi-module applications, here it helps us to better organize all of the projects. This structure allows all of the child projects to make use of the plugins that are defined in the parent `pom.xml` file, without having to define them again in the child `pom.xml` files.

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +Now you can develop the application and the different modules together using the Liberty Maven plug-in development mode.
You can now develop the application and the different modules together in dev mode by using the Liberty Maven plug-in.

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +To learn more about to use development mode with multiple modules, check out the link:https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md#multiple-modules[Documentation].
To learn more about to use...
--->
To learn more about how to use...

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +Because you started Open Liberty in development mode, press the `enter/return key` to run the tests.
`enter/return key`
--->
**enter/return** key

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +When you are done checking out the service, exit dev mode by pressing `CTRL+C` in the command-line session where you ran the server,
should consistently use either "dev mode" or "development mode". Recommend "development mode" here based on precedent

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +or by typing `q` and then pressing the `enter/return` key.
typing `q` and then pressing the `enter/return` key.
-->
typing **q** and then pressing the **enter/return** key.

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +You have aggregated and developed the application. Now, you can run `mvn install` once from the `start` directory and it will automatically build all your modules. This command creates a JAR file in
You have aggregated and developed the application
--->
You aggregated and developed the application

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +You have aggregated and developed the application. Now, you can run `mvn install` once from the `start` directory and it will automatically build all your modules. This command creates a JAR file in
This command creates a JAR file in the `jar/target` directory, a WAR file in the `war/target` directory, and an EAR file that contains the JAR and WAR files in the `ear/target` directory.

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +Use the following command to build the entire application from the `start` directory:
Use the following command to build the entire application from the `start` directory:
--->
Run the following command  from the `start` directory to build the entire application:

2021-10-25 21:04 UTC, dmuelle commented on README.adoc
> +Since the modules are independent, you can re-build them individually by running `mvn install` from the corresponding module directory.
from the corresponding module directory.
--->
from the corresponding `start` directory for each module.

2021-10-28 15:20 UTC, ryan-storey commented on README.adoc
> +To deploy your EAR application on an Open Liberty server, run the Maven `liberty:run` goal from the `finish` directory using the `-pl ear` or `--projects ear` flag:
@gkwan-ibm what should we do here? originally we just had `-pl ear`

2021-10-28 16:03 UTC, gkwan-ibm commented on README.adoc
> +To deploy your EAR application on an Open Liberty server, run the Maven `liberty:run` goal from the `finish` directory using the `-pl ear` or `--projects ear` flag:
@dmuelle  
yes, `-pl ear` and `--projects ear` are identical. We provide both because some users may not know what `-pl` stands for.  Showing `--projects`, users may aware what `-pl` equivalent to it. And, we only mention at the first occurrence of `-pl`. If this is not a good reason, we can remove the phase  `--projects ear`, and reword the statement like following (please correct my words):
>To deploy your EAR application on an Open Liberty server, run the Maven `liberty:run` goal from the `finish` directory using the `-pl ear` flag. Use `-pl` flag to specify which project the maven command to run on.

2021-10-28 16:24 UTC, dmuelle commented on README.adoc
> +To deploy your EAR application on an Open Liberty server, run the Maven `liberty:run` goal from the `finish` directory using the `-pl ear` or `--projects ear` flag:
I guess it could work either way, though there's a possibility some users might wonder which syntax to use and whether they are identical. If the `pl` abbreviation is the more common syntax, I'd recommend something like:

"To deploy your EAR application on an Open Liberty server, run the Maven `liberty:run` goal from the `finish` directory using the `-pl` flag to specify the `ear` project. The -pl flag specifies the project where  the maven goal runs."

In this example, the `ear` project is in the `finish` directory?

2021-10-28 17:01 UTC, gkwan-ibm commented on README.adoc
> +To deploy your EAR application on an Open Liberty server, run the Maven `liberty:run` goal from the `finish` directory using the `-pl ear` or `--projects ear` flag:
I am ok the suggested wording "The `-pl` flag..."

Yes In this example, the ear project is in the finish directory.

2021-11-03 16:59 UTC, dmuelle approved these changes
LGTM

2021-11-03 21:31 UTC, merged